# Location of the project directory
$the_vagrant_project_dir = "#{__dir__}"

# Location of the-vagrant's config file
$the_vagrant_config = "#{__dir__}/.the-vagrant.yml"

# Load the real Vagrantfile
load "#{__dir__}/vendor/palantirnet/the-vagrant/Vagrantfile"
